package com.care.KorTravel.service;


import org.springframework.stereotype.Service;

@Service
public class MailForm {
	
	
	
	public String mailForm(String number) {

		
		 StringBuffer sb = new StringBuffer();
		  sb.append("<html><body>");
		  sb.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
		  		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
		  		+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
		  		+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
		  		+ "  <title></title>\r\n"
		  		+ "  \r\n"
		  		+ "    <style type=\"text/css\">\r\n"
		  		+ "      @media only screen and (min-width: 670px) {\r\n"
		  		+ "  .u-row {\r\n"
		  		+ "    width: 650px !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-row .u-col {\r\n"
		  		+ "    vertical-align: top;\r\n"
		  		+ "  }\r\n"
		  		+ "\r\n"
		  		+ "  .u-row .u-col-100 {\r\n"
		  		+ "    width: 650px !important;\r\n"
		  		+ "  }\r\n"
		  		+ "\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "@media (max-width: 670px) {\r\n"
		  		+ "  .u-row-container {\r\n"
		  		+ "    max-width: 100% !important;\r\n"
		  		+ "    padding-left: 0px !important;\r\n"
		  		+ "    padding-right: 0px !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-row .u-col {\r\n"
		  		+ "    min-width: 320px !important;\r\n"
		  		+ "    max-width: 100% !important;\r\n"
		  		+ "    display: block !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-row {\r\n"
		  		+ "    width: calc(100% - 40px) !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-col {\r\n"
		  		+ "    width: 100% !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-col > div {\r\n"
		  		+ "    margin: 0 auto;\r\n"
		  		+ "  }\r\n"
		  		+ "}\r\n"
		  		+ "body {\r\n"
		  		+ "  margin: 0;\r\n"
		  		+ "  padding: 0;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "table,\r\n"
		  		+ "tr,\r\n"
		  		+ "td {\r\n"
		  		+ "  vertical-align: top;\r\n"
		  		+ "  border-collapse: collapse;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "p {\r\n"
		  		+ "  margin: 0;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ ".ie-container table,\r\n"
		  		+ ".mso-container table {\r\n"
		  		+ "  table-layout: fixed;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "* {\r\n"
		  		+ "  line-height: inherit;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "a[x-apple-data-detectors='true'] {\r\n"
		  		+ "  color: inherit !important;\r\n"
		  		+ "  text-decoration: none !important;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "table, td { color: #000000; } #u_body a { color: #0000ee; text-decoration: underline; }\r\n"
		  		+ "    </style>\r\n"
		  		+ "  \r\n"
		  		+ "  \r\n"
		  		+ "\r\n"
		  		+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
		  		+ "\r\n"
		  		+ "</head>\r\n"
		  		+ "\r\n"
		  		+"<script>\r\n"
		  		+ "function plus(){\r\n"
		  		+ "	alert('hi');\r\n"
		  		+ "}\r\n"
		  		+ "</script>"
		  		
		  		
		  		+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000\">\r\n"
		  		+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
		  		+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
		  		+ "  <table id=\"u_body\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "  <tr style=\"vertical-align: top\">\r\n"
		  		+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
		  		+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #ffffff;\"><![endif]-->\r\n"
		  		+ "    \r\n"
		  		+ "\r\n"
		  		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
		  		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #dff1ff;\">\r\n"
		  		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\r\n"
		  		+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #dff1ff;\"><![endif]-->\r\n"
		  		+ "      \r\n"
		  		+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
		  		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\r\n"
		  		+ "  <div style=\"height: 100%;width: 100% !important;\">\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
		  		+ "  \r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
		  		+ "  <tr>\r\n"
		  		+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
		  		+ "      \r\n"
		  		+ "      <img onclick=\"plus()\" align=\"center\" border=\"0\" src=\"cid:image2\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 24%;max-width: 156px;\" width=\"156\"/>\r\n"
		  		+ "      \r\n"
		  		+ "    </td>\r\n"
		  		+ "  </tr>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #018eea; line-height: 170%; text-align: left; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 170%; text-align: center;\"><span style=\"font-size: 24px; line-height: 40.8px;\"><strong><span style=\"line-height: 40.8px; font-size: 24px;\">인증번호</span></strong></span></p>\r\n"
		  		+ "<p style=\"font-size: 14px; line-height: 170%; text-align: center;\"><span style=\"font-size: 20px; line-height: 34px;\"><span style=\"line-height: 34px; font-size: 20px;\">빨리 인증번호 입력하고 가입하러 가기</span></span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
		  		+ "  <tr>\r\n"
		  		+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
		  		+ "      \r\n"
		  		+ "      <img align=\"center\" border=\"0\" src=\"cid:image1\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 650px;\" width=\"650\"/>\r\n"
		  		+ "      \r\n"
		  		+ "    </td>\r\n"
		  		+ "  </tr>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
		  		+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
		  		+ "    </div>\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
		  		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f3fbfd;\">\r\n"
		  		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\r\n"
		  		+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #f3fbfd;\"><![endif]-->\r\n"
		  		+ "      \r\n"
		  		+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
		  		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\r\n"
		  		+ "  <div style=\"height: 100%;width: 100% !important;\">\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
		  		+ "  \r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #1b262c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%;\"><strong><span style=\"font-size: 26px; line-height: 36.4px;\">반갑습니다. 대한민국 방방곡곡입니다!</span></strong></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px 20px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #1b262c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 16px; line-height: 22.4px;\">회원가입하시면 다양한 관광지 정보와 여행 계획을 간편히 수립하실 수 있습니다!</span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <!--[if mso]><style>.v-button {background: transparent !important;}</style><![endif]-->\r\n"
		  		+ "<div align=\"center\">\r\n"
		  		+ "  <!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:37px; v-text-anchor:middle; width:96px;\" arcsize=\"11%\"  stroke=\"f\" fillcolor=\"#3AAEE0\"><w:anchorlock/><center style=\"color:#ffffff;font-family:'Montserrat',sans-serif;\"><![endif]-->  \r\n"
		  		+ "    <a href=\"\" target=\"_blank\" class=\"v-button\" style=\"box-sizing: border-box;display: inline-block;font-family:'Montserrat',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffffff; background-color: #3AAEE0; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
		  		+ "      <span  style=\"display:block;padding:10px 20px;line-height:120%;\"><span  style=\"font-size: 14px; line-height: 16.8px;\">"+number+"</span></span>\r\n"
		  		+ "    </a>\r\n"
		  		+ "  <!--[if mso]></center></v:roundrect><![endif]-->\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:18px 50px 50px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #5f5f5f; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 12px; line-height: 16.8px;\">We don't send any irrelevant email or sell your data &amp; you can unsubscribe any time.</span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
		  		+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
		  		+ "    </div>\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
		  		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #151418;\">\r\n"
		  		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\r\n"
		  		+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #151418;\"><![endif]-->\r\n"
		  		+ "      \r\n"
		  		+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
		  		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\r\n"
		  		+ "  <div style=\"height: 100%;width: 100% !important;\">\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
		  		+ "  \r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:18px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 14px; line-height: 19.6px;\">Copyright Your company | All RIghts Reserved</span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
		  		+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
		  		+ "    </div>\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
		  		+ "    </td>\r\n"
		  		+ "  </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "  </table>\r\n"
		  		+ "  <!--[if mso]></div><![endif]-->\r\n"
		  		+ "  <!--[if IE]></div><![endif]-->\r\n"
		  		+ "</body>\r\n"
		  		+ "\r\n"
		  		+ "</html>");
		  String str=sb.toString();
		 
		  return str;


		


	}
	public String mailForm2(String number,String id) {

		
		 StringBuffer sb = new StringBuffer();
		  sb.append("<html><body>");
		  sb.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
		  		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
		  		+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
		  		+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
		  		+ "  <title></title>\r\n"
		  		+ "  \r\n"
		  		+ "    <style type=\"text/css\">\r\n"
		  		+ "      @media only screen and (min-width: 670px) {\r\n"
		  		+ "  .u-row {\r\n"
		  		+ "    width: 650px !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-row .u-col {\r\n"
		  		+ "    vertical-align: top;\r\n"
		  		+ "  }\r\n"
		  		+ "\r\n"
		  		+ "  .u-row .u-col-100 {\r\n"
		  		+ "    width: 650px !important;\r\n"
		  		+ "  }\r\n"
		  		+ "\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "@media (max-width: 670px) {\r\n"
		  		+ "  .u-row-container {\r\n"
		  		+ "    max-width: 100% !important;\r\n"
		  		+ "    padding-left: 0px !important;\r\n"
		  		+ "    padding-right: 0px !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-row .u-col {\r\n"
		  		+ "    min-width: 320px !important;\r\n"
		  		+ "    max-width: 100% !important;\r\n"
		  		+ "    display: block !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-row {\r\n"
		  		+ "    width: calc(100% - 40px) !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-col {\r\n"
		  		+ "    width: 100% !important;\r\n"
		  		+ "  }\r\n"
		  		+ "  .u-col > div {\r\n"
		  		+ "    margin: 0 auto;\r\n"
		  		+ "  }\r\n"
		  		+ "}\r\n"
		  		+ "body {\r\n"
		  		+ "  margin: 0;\r\n"
		  		+ "  padding: 0;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "table,\r\n"
		  		+ "tr,\r\n"
		  		+ "td {\r\n"
		  		+ "  vertical-align: top;\r\n"
		  		+ "  border-collapse: collapse;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "p {\r\n"
		  		+ "  margin: 0;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ ".ie-container table,\r\n"
		  		+ ".mso-container table {\r\n"
		  		+ "  table-layout: fixed;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "* {\r\n"
		  		+ "  line-height: inherit;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "a[x-apple-data-detectors='true'] {\r\n"
		  		+ "  color: inherit !important;\r\n"
		  		+ "  text-decoration: none !important;\r\n"
		  		+ "}\r\n"
		  		+ "\r\n"
		  		+ "table, td { color: #000000; } #u_body a { color: #0000ee; text-decoration: underline; }\r\n"
		  		+ "    </style>\r\n"
		  		+ "  \r\n"
		  		+ "  \r\n"
		  		+ "\r\n"
		  		+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
		  		+ "\r\n"
		  		+ "</head>\r\n"
		  		+ "\r\n"
		  		+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000\">\r\n"
		  		+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
		  		+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
		  		+ "  <table id=\"u_body\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "  <tr style=\"vertical-align: top\">\r\n"
		  		+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
		  		+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #ffffff;\"><![endif]-->\r\n"
		  		+ "    \r\n"
		  		+ "\r\n"
		  		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
		  		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #dff1ff;\">\r\n"
		  		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\r\n"
		  		+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #dff1ff;\"><![endif]-->\r\n"
		  		+ "      \r\n"
		  		+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
		  		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\r\n"
		  		+ "  <div style=\"height: 100%;width: 100% !important;\">\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
		  		+ "  \r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
		  		+ "  <tr>\r\n"
		  		+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
		  		+ "      \r\n"
		  		+ "      <img align=\"center\" border=\"0\" src=\"cid:image2\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 24%;max-width: 156px;\" width=\"156\"/>\r\n"
		  		+ "      \r\n"
		  		+ "    </td>\r\n"
		  		+ "  </tr>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #018eea; line-height: 170%; text-align: left; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 170%; text-align: center;\"><span style=\"font-size: 24px; line-height: 40.8px;\"><strong><span style=\"line-height: 40.8px; font-size: 24px;\">인증번호</span></strong></span></p>\r\n"
		  		+ "<p style=\"font-size: 14px; line-height: 170%; text-align: center;\"><span style=\"font-size: 20px; line-height: 34px;\"><span style=\"line-height: 34px; font-size: 20px;\">아이디/비밀번호 찾기</span></span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
		  		+ "  <tr>\r\n"
		  		+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
		  		+ "      \r\n"
		  		+ "      <img onclick=\"plus()\" align=\"center\" border=\"0\" src=\"cid:image1\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 650px;\" width=\"650\"/>\r\n"
		  		+ "      \r\n"
		  		+ "    </td>\r\n"
		  		+ "  </tr>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
		  		+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
		  		+ "    </div>\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
		  		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f3fbfd;\">\r\n"
		  		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\r\n"
		  		+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #f3fbfd;\"><![endif]-->\r\n"
		  		+ "      \r\n"
		  		+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
		  		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\r\n"
		  		+ "  <div style=\"height: 100%;width: 100% !important;\">\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
		  		+ "  \r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #1b262c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%;\"><strong><span style=\"font-size: 26px; line-height: 36.4px;\">반갑습니다. 대한민국 방방곡곡입니다!</span></strong></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px 20px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #1b262c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 16px; line-height: 22.4px;\">회원님의 아이디는 <b>"+id+"</b>입니다.</span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <!--[if mso]><style>.v-button {background: transparent !important;}</style><![endif]-->\r\n"
		  		+ "<div align=\"center\">\r\n"
		  		+ "  <!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:37px; v-text-anchor:middle; width:96px;\" arcsize=\"11%\"  stroke=\"f\" fillcolor=\"#3AAEE0\"><w:anchorlock/><center style=\"color:#ffffff;font-family:'Montserrat',sans-serif;\"><![endif]-->  \r\n"
		  		+ "    <a href=\"\" target=\"_blank\" class=\"v-button\" style=\"box-sizing: border-box;display: inline-block;font-family:'Montserrat',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #ffffff; background-color: #3AAEE0; border-radius: 4px;-webkit-border-radius: 4px; -moz-border-radius: 4px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
		  		+ "      <span style=\"display:block;padding:10px 20px;line-height:120%;\"><span style=\"font-size: 14px; line-height: 16.8px;\">"+number+"</span></span>\r\n"
		  		+ "    </a>\r\n"
		  		+ "  <!--[if mso]></center></v:roundrect><![endif]-->\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:18px 50px 50px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #5f5f5f; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 12px; line-height: 16.8px;\">We don't send any irrelevant email or sell your data &amp; you can unsubscribe any time.</span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
		  		+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
		  		+ "    </div>\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
		  		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 650px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #151418;\">\r\n"
		  		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;height: 100%;background-color: transparent;\">\r\n"
		  		+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:650px;\"><tr style=\"background-color: #151418;\"><![endif]-->\r\n"
		  		+ "      \r\n"
		  		+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"650\" style=\"width: 650px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
		  		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 650px;display: table-cell;vertical-align: top;\">\r\n"
		  		+ "  <div style=\"height: 100%;width: 100% !important;\">\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
		  		+ "  \r\n"
		  		+ "<table style=\"font-family:'Montserrat',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
		  		+ "  <tbody>\r\n"
		  		+ "    <tr>\r\n"
		  		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:18px;font-family:'Montserrat',sans-serif;\" align=\"left\">\r\n"
		  		+ "        \r\n"
		  		+ "  <div style=\"color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
		  		+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 14px; line-height: 19.6px;\">Copyright Your company | All RIghts Reserved</span></p>\r\n"
		  		+ "  </div>\r\n"
		  		+ "\r\n"
		  		+ "      </td>\r\n"
		  		+ "    </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "</table>\r\n"
		  		+ "\r\n"
		  		+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
		  		+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
		  		+ "    </div>\r\n"
		  		+ "  </div>\r\n"
		  		+ "</div>\r\n"
		  		+ "\r\n"
		  		+ "\r\n"
		  		+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
		  		+ "    </td>\r\n"
		  		+ "  </tr>\r\n"
		  		+ "  </tbody>\r\n"
		  		+ "  </table>\r\n"
		  		+ "  <!--[if mso]></div><![endif]-->\r\n"
		  		+ "  <!--[if IE]></div><![endif]-->\r\n"
		  		+ "</body>\r\n"
		  		+ "\r\n"
		  		+ "</html>");
		  String str=sb.toString();
		 
		  return str;


		


	}

}
